# Generated by Django 5.1.1 on 2024-12-12 02:57

import datetime
import info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_bannermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(null=True, upload_to=info.models.upload_to, verbose_name='首页左下文件')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页左下文件表',
                'verbose_name_plural': '首页左下文件表',
            },
        ),
    ]
