# Generated by Django 5.1.1 on 2024-12-16 02:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_file1model'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='新闻内容')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='新闻图片')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻管理',
                'ordering': ['-pub_date'],
            },
        ),
    ]
