# Generated by Django 5.1.1 on 2024-12-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_department_userprofile_desp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('section', models.CharField(max_length=100, verbose_name='涉及板块')),
                ('analysis_type', models.CharField(max_length=100, verbose_name='分析大类')),
                ('analysis_detail', models.CharField(max_length=100, verbose_name='分析细类')),
                ('urgency', models.CharField(choices=[('very', '非常紧急（需3天内完成）'), ('moderate', '较紧急（3-7天）'), ('normal', '一般紧急（7天以上）')], max_length=20, verbose_name='紧急程度')),
                ('content', models.TextField(verbose_name='具体内容')),
                ('department', models.CharField(max_length=100, verbose_name='需求科室')),
                ('contact_person', models.CharField(max_length=100, verbose_name='对接人员')),
                ('contact_info', models.CharField(max_length=100, verbose_name='联系方式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '需求表单',
                'verbose_name_plural': '需求表单',
                'ordering': ['-submit_time'],
            },
        ),
    ]
